service:
  label:
    "stargazer-test-node-1"
  http:
    addr: "0.0.0.0"
    port: 8080
  log_level: # debug, info, error
    "info"

data:
  database:
#    only support sqlite3 now
    driver: "sqlite3"
    connection: "/data/sqlite3/stargazer.db"

swagger:
  enabled: false
  addr: "127.0.0.1"
  port: 8081