/*
 * Stargazer
 *
 * Stargazer Backend OpenAPI Specification
 *
 * API version: 0.1.0
 * Contact: sptuan@steinslab.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"fmt"
	"github.com/sptuan/stargazer/internal/constant"
	"github.com/sptuan/stargazer/internal/dao"
	"github.com/sptuan/stargazer/internal/entity"
	"github.com/sptuan/stargazer/pkg/logger"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// GetDataLogByTaskId - Get data log by task ID
func GetDataLogByTaskId(c *gin.Context) {
	// parse task id, start, end
	taskIdStr := c.Param("taskId")
	taskId, err := strconv.Atoi(taskIdStr)
	if err != nil {
		logger.Errorf("GetDataLogByTaskId: %v", err)
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	level := c.Query("level")

	var start, end int
	startStr := c.Query("start")
	if startStr != "" {
		start, err = strconv.Atoi(startStr)
		if err != nil {
			logger.Errorf("GetDataLogByTaskId: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
	} else {
		start = int(time.Now().Add(-1 * time.Hour).Unix())
	}

	endStr := c.Query("end")
	if endStr != "" {
		end, err = strconv.Atoi(endStr)
		if err != nil {
			logger.Errorf("GetDataLogByTaskId: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
	} else {
		end = int(time.Now().Unix())
	}

	dataLog := []entity.DataLog{}

	if level == "" {
		dataLog, err = dao.GetDataLogByTaskIdInTimeRange(taskId, start, end)
		if err != nil {
			logger.Errorf("GetDataLogByTaskId: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
	} else {
		dataLog, err = dao.GetDataLogByTaskIdLevelInTimeRange(taskId, constant.Level(level), start, end)
		if err != nil {
			logger.Errorf("GetDataLogByTaskId: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
	}

	c.JSON(http.StatusOK, gin.H{"log": dataLog})
}

// parseDataLogQuery - parse query params for data log
func parseDataLogQuery(c *gin.Context) (int, int, int, int, error) {
	taskId, err := strconv.Atoi(c.Param("taskId"))
	if err != nil {
		return 0, 0, 0, 0, err
	}

	// parse interval
	interval, err := strconv.Atoi(c.Query("interval"))
	if err != nil {
		return 0, 0, 0, 0, err
	}

	// parse start
	start, err := strconv.Atoi(c.Query("start"))
	if err != nil {
		return 0, 0, 0, 0, err
	}

	// parse end
	end, err := strconv.Atoi(c.Query("end"))
	if err != nil {
		return 0, 0, 0, 0, err
	}

	return taskId, interval, start, end, nil
}

// GetDataSeriesByTaskId - Get data series by task ID
func GetDataSeriesByTaskId(c *gin.Context) {
	taskId, interval, start, end, err := parseDataLogQuery(c)
	if err != nil {
		logger.Errorf("GetDataSeriesByTaskId: %v", err)
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// get data log
	dataLog, err := dao.GetDataLogByTaskIdInTimeRange(taskId, start, end)
	var dataSeries []DataSeries

	index := 0
	for st := start; st < end+interval; st += interval {
		var dataSeriesItem DataSeries
		dataSeriesItem.TimeStart = int64(st)
		dataSeriesItem.TimeEnd = int64(st + interval)

		HealtyCounter := 0
		UnhealtyCounter := 0
		msg := strings.Builder{}
		for dataLog[index].Time < st+interval {
			if constant.INFO == constant.Level(dataLog[index].Level) {
				HealtyCounter++
			} else {
				UnhealtyCounter++
				timeHuman := time.Unix(int64(dataLog[index].Time), 0).Format("2006-01-02 15:04:05")
				msg.WriteString(fmt.Sprintf("%s:%s, %s)", timeHuman, dataLog[index].Level, dataLog[index].Message))
			}
			index++
		}
		dataSeriesItem.Value = float32(HealtyCounter) / float32(HealtyCounter+UnhealtyCounter)
		dataSeries = append(dataSeries, dataSeriesItem)
	}

	c.JSON(http.StatusOK, gin.H{"series": dataSeries})
}

// GetDataStatusByTaskId - Get data status by task ID
func GetDataStatusByTaskId(c *gin.Context) {
	idStr := c.Param("taskId")
	id, err := strconv.Atoi(idStr)
	if err != nil {
		logger.Errorf("GetDataStatusByTaskId: %v", err)
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	dataStatus, err := dao.GetDataLogLastByTaskId(id)
	if err != nil {
		logger.Errorf("GetDataStatusByTaskId: %v", err)
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, gin.H{"status": dataStatus})
}
