/*
 * Stargazer
 *
 * Stargazer Backend OpenAPI Specification
 *
 * API version: 0.1.0
 * Contact: sptuan@steinslab.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type DataLog struct {
	Time int64 `json:"time,omitempty"`

	Level string `json:"level,omitempty"`
}
