/*
 * Stargazer
 *
 * Stargazer Backend OpenAPI Specification
 *
 * API version: 0.1.0
 * Contact: sptuan@steinslab.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"GetDataLogByTaskId",
		http.MethodGet,
		"/data/:taskId/log",
		GetDataLogByTaskId,
	},

	{
		"GetDataSeriesByTaskId",
		http.MethodGet,
		"/data/:taskId/series",
		GetDataSeriesByTaskId,
	},

	{
		"GetDataStatusByTaskId",
		http.MethodGet,
		"/data/:taskId/status",
		GetDataStatusByTaskId,
	},

	{
		"AddTask",
		http.MethodPost,
		"/task",
		AddTask,
	},

	{
		"DeleteTaskById",
		http.MethodDelete,
		"/task/:taskId",
		DeleteTaskById,
	},

	{
		"GetTaskById",
		http.MethodGet,
		"/task/:taskId",
		GetTaskById,
	},

	{
		"GetTasks",
		http.MethodGet,
		"/task",
		GetTasks,
	},

	{
		"UpdateTaskById",
		http.MethodPut,
		"/task/:taskId",
		UpdateTaskById,
	},
}
