/*
 * Stargazer
 *
 * Stargazer Backend OpenAPI Specification
 *
 * API version: 0.1.0
 * Contact: sptuan@steinslab.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddTask - Add a new task
func AddTask(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteTaskById - Delete task by ID
func DeleteTaskById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTaskById - Get task by ID
func GetTaskById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTasks - Get all tasks
func GetTasks(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateTaskById - Update task by ID
func UpdateTaskById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
