/*
 * Stargazer
 *
 * Stargazer Backend OpenAPI Specification
 *
 * API version: 0.1.0
 * Contact: sptuan@steinslab.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type DataSeries struct {
	TimeStart int64 `json:"time_start,omitempty"`

	TimeEnd int64 `json:"time_end,omitempty"`

	Value float32 `json:"value,omitempty"`

	Message string `json:"message,omitempty"`
}
